language: objective-c

osx_image: xcode8

rvm:
  - 2.2.2

before_install:
 - gem install cocoapods -v '1.0.1'
 - brew update
 - brew outdated xctool || brew upgrade xctool

script:
 - xcodebuild -workspace ZypeAppleTVBase.xcworkspace -scheme ZypeAppleTVBase -sdk appletvsimulator10.0 ONLY_ACTIVE_ARCH=NO